# Generated by Django 6.0.3 on 2026-03-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
