# Generated by Django 4.2.11 on 2026-09-17 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='availability_status',
            field=models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('On Leave', 'On Leave')], default='Available', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='certifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, default='Engineering', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(blank=True, default='Talent Specialist', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='skill_levels',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='weekly_capacity_hours',
            field=models.IntegerField(default=40),
        ),
    ]
