# Generated by Django 4.2.7 on 2026-04-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_assigned_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Submitted', 'Submitted'), ('Reviewed', 'Reviewed'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
